package votingLibrary;

public enum VotingType {
    PR_HARE, PR_DROOP, PR_HARE_PROVINCE, PR_DROOP_PROVINCE, PR_HARE_NATIONAL, PR_DROOP_NATIONAL,
    FPTP, FPTP_PROVINCE, FPTP_NATIONAL,
    MMP_DHONDT_PROVINCE, MMP_SAINTELAGUE_PROVINCE, MMP_DHONDT_NATIONAL, MMP_SAINTELAGUE_NATIONAL,
    MMM_HARE_PROVINCE, MMM_DROOP_PROVINCE, MMM_HARE_NATIONAL, MMM_DROOP_NATIONAL
}
